/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.rs"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#fff0ee",
        "on-surface-variant": "#5a413c",
        tertiary: "#595a5f",
        "on-tertiary-fixed-variant": "#45474b",
        "on-primary-fixed-variant": "#8f1202",
        "on-secondary-fixed-variant": "#910906",
        error: "#ba1a1a",
        surface: "#fff8f6",
        "on-tertiary-container": "#faf9ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb4a6",
        "inverse-surface": "#3c2d2a",
        "surface-container-high": "#fde2dd",
        "surface-container-highest": "#f7ddd8",
        secondary: "#b4281c",
        "surface-dim": "#eed4d0",
        "on-tertiary-fixed": "#1a1c1f",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-container": "#610001",
        "surface-tint": "#b12c19",
        "on-primary-container": "#fff8f7",
        "inverse-primary": "#ffb4a6",
        "secondary-fixed-dim": "#ffb4a8",
        outline: "#8e706b",
        "on-background": "#261816",
        "surface-bright": "#fff8f6",
        primary: "#ab2815",
        "outline-variant": "#e2bfb8",
        "tertiary-container": "#717377",
        "tertiary-fixed": "#e2e2e7",
        "secondary-container": "#fe5d4a",
        "on-error": "#ffffff",
        "on-primary-fixed": "#3f0300",
        "surface-container": "#ffe9e5",
        "surface-variant": "#f7ddd8",
        "on-surface": "#261816",
        "tertiary-fixed-dim": "#c6c6cb",
        "on-secondary-fixed": "#410000",
        "inverse-on-surface": "#ffede9",
        "error-container": "#ffdad6",
        "primary-container": "#ce412b",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdad4",
        "on-secondary": "#ffffff",
        background: "#fff8f6",
        "secondary-fixed": "#ffdad5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        cell_padding_h: "12px",
        sidebar_width: "240px",
        gutter: "1rem",
        cell_padding_v: "10px",
        margin_page: "1.5rem",
        drawer_width: "480px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-xs": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "code-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-xs": ["11px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "code-md": [
          "13px",
          { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
